INSERT INTO item (item_id, item_group_id, name, description, price) VALUES (1, 101, 'Mobil 1 High Mileage Full Synthetic Motor Oil 5W-30, 5 Quart', NULL, 27.47);
INSERT INTO item (item_id, item_group_id, name, description, price) VALUES (2, 101, 'Mobil 1 High Mileage Full Synthetic Motor Oil 10W-40, 5 Quart', NULL, 27.47);
INSERT INTO item (item_id, item_group_id, name, description, price) VALUES (3, 101, 'Castrol Edge 5W-20 Advanced Full Synthetic Motor Oil, 5 Quarts', NULL, 27.94);
INSERT INTO item (item_id, item_group_id, name, description, price) VALUES (4, 102, 'FRAM Extra Guard Filter PH10575, 10K mile Change Interval Oil Filter', NULL, 6.63);
INSERT INTO item (item_id, item_group_id, name, description, price) VALUES (5, 102, 'Mobil 1 M1-110A Extended Performance Oil Filter', NULL, 9.97);
INSERT INTO item (item_id, item_group_id, name, description, price) VALUES (6, 102, 'Super Tech 10K mile Spin-On Oil Filter, ST6607, for Honda and Infiniti Vehicles', NULL, 3.42);
INSERT INTO item (item_id, item_group_id, name, description, price) VALUES (7, 103, 'Goodyear Reliant All-Season 235/60R17 102H Tire', NULL, 112.0);
INSERT INTO item (item_id, item_group_id, name, description, price) VALUES (8, 103, 'Cooper Discoverer A/T All-Season LT265/70R17 121S Tire', NULL, 140.05);
INSERT INTO item (item_id, item_group_id, name, description, price) VALUES (9, 103, 'Douglas All-Season 215/60R16 95H Tire', NULL, 68.0);
INSERT INTO item_group (item_group_id, item_group_name, description) VALUES (101, 'Engine Oil', 'n/a');
INSERT INTO item_group (item_group_id, item_group_name, description) VALUES (102, 'Oil Filters', 'n/a');
INSERT INTO item_group (item_group_id, item_group_name, description) VALUES (201, 'Tires', 'n/a');